language: node_js
node_js: '8'
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: krH6JG8kuU8gt+fAhSD7WLo1PS9aYul1W+TX1BCs7kENWJ0TQufvXVe3TZ4dbEsvJKoXQ23kWAOTSHHDm0Bvqf+Rhq81No7zIjBb6MY/JwSmxMWMLksoQ4CWIbWDgTHq8ek0sBO3BQPvJcruZpFlbPMlHdRBmscl4cWedqfY6AIGnxYWNKAJ61dqgJKKEXehHsdBQQ+l3uQHpfAsOUT74s/8hjJ8V8fssMHcw8tFJ4JtMHGN7ONk9bk1YRtctb3yyffzaabVybtHxqQB60X3zueJOS5oEZY6tDcp4NRCppIZu5LhY5fnOLWjadR0KnrNKb30f2H0/D5AduXJ9Uneef255bpdnHBZ7rYmmrMGKSFVTytAkbmd7++F6i4l9DkY/2/iXROxBbTMlIet6AVdERmPt44fMEtG3zjkZhb0fX4QoJJRB5RxvMRvUFCpfC0sgVa9tBrcKWJh3b7DBn4IXbkTiIqLIK5+Z1jP5s/w1RjGXamCE3ERZ/REr5jT8QfhnrfkAHIjjW5bmJ+4dY8455ey2JEMHk4l5uQ0lUNT5y56ol8cTJYMGTfhBDs9h7u0UssER7M/SSlxLs0Ktbq+QySvod/KbP9Lc+qPzo0BrmmlBBT7s5tOt0zDtBInyhWNhSBjn6F7Imfv3y21fX4UoJu/fcENbN7Nc8eSStBFWPg=
  app: tasks-and-treasures-client
  on:
    repo: dermio/tasks-and-treasures-client
