language: node_js
node_js: '8'
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: oLJaUsIFnsyGsIbiWT4FmTI65LDTWgqdFqx+9C6Rb9g7vQqympmHpt9+Z1NBQYpVNVKYujScH0+wGFGIlMIlY152S97/kgYBdhhdOpkwxJ42s7hCO2wWkaZwd4CaapB2NaW7Hy7DzW5g76O9WwBrReQHXobktcFB0wjCoNQ/uV/lbV/jecUbDubE0w2rx9SNVwHlSQQq2dVImA4dGWZzDH3VZyZJTfxbWCP+PADIO3zP3/gBimNvESw7BCeEwL36o+/mCKZixKcHfpSFdVS4YbXGBo/N8zE1F0swbZ2Z3Po/XS8GirtYu/72j+u66qCBXEgy9gql4ENOGHIkB4wYs2RmjBj4MnF4gHKysrUqcZJY1SVGC7ZP63fHoHJ4S7F5r25gOzPr5uzekN60uSPOvol1x2ruB/KQI+EQS6C/2auZl65TXFy2eom8OkMznlUFnGbB43SC5R/gyw6ijT8KJ8TbJGfUHhsXNTvFJMGcJ9GCl9BidspjkPdhsujl11KiYNyG4UnTXFuRGehkuW2ijej8t5FMlLbJWYuXmnk8+O1ynttDlrDKilHeumRcBS7gKZWvArCf66bY0OyfbpcODAv4x1Z9iaFchS79iX7h2KHefsFBrDBs3a+u7gsZkzioYY4aUHPYIlr3T+K5lGQtjV5zeDfMEa5MzsuagV0wb/E=
  app: tasks-and-treasures-client
  on:
    repo: dermio/tasks-and-treasures-client
