language: node_js
node_js: '8'
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: aeq35wTYVlnERxyuhdtBK6zjQKcKR4SHs+F8YgSStOl2Sn3ZMvfn6/PW/58wkY+JeFHqx5qdPeClsGK3/9drqyYKuxbkISyIcLsbbI2DzOFXwP5iE9gteCAiYOppAz+8i6HFaE+XqZOZX1/MNJ+mvNQf3XCFGvZQg7mNenvKahY+hSKGJt/F7Cbx7s9eOxkR8pqmyeoJracG7n0ihhVtJOWF8np8pfYccrmer03OvFDI8kcmZ2cWzYxrv+7f5Qduu2fGSyi11yLPCsYC+MvR7d0PVRI7vf4jL7HO/iazQCsO5V7m+CV4W4ZnungPhzMG/j5YCZNua3U9fKBLBk/D5QrydiC9h6vd+P33cdVCS4RN1Lt6rh06gXQ/FEtsGA4PK7t6VyaP5DmqBvriUvRGtR8W67NlwgFnoTOv8snDQxI1Rsow8XyXpCoUAKVwoc9MrkTIOgrY8eY22m/WMtcNT7ISye+OzZ2gs2AZrXXs+lm2tDP9EousZEaivTE43zePE9ny6ijMoikCNscp1Cau5XMp8nz1dHHzx1cb1rFt2AtFkaai2uM4XuoAki1AK0bOzZcWXDU39/GE7yr5fCJUQLmYPJ73QP2wx6solnbywPWd53GKQMeUvHgafeh7/DKTOx6ZYG+VUQj8xAReXtFvbuG6u+t5Te/y+IgMXsSIXok=
  app: tasks-and-treasures-client
  on:
    repo: dermio/tasks-and-treasures-client
