language: node_js
node_js: '8'
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: oI9pqLx7wnrTYjTl8AzE63Ky768YuwJ45KdWxNJI4dtGxiFWrCjSI0g9w43VrG/r0SY5+ufd8IVryaqKmgr17p2X7BwSIPMY4PbuBx0pxz4/E8+TE0lNhcx531qOImhvlQTPejIBJZoalqw7w/4cLBeEL3ufGuEfeDJ93/jp6CK18RpKJ6NF/pn3+4RZG/D8UY0H+9vjqkb6f9ww+cPaGwpMKCaZAl9yiuYR+5uROcgvKqGm+705Rqi2wQs7oYdaOj2jAHwUbtDOQ82K48H+MfsiZ5e5md5Hp/QCeEGDBYeMUnQYU5zYejOc2LUSzJ752eSCAJeN1Rl57ojGTFKiLtSVMZcbbMvEAwtbvw3J1kItnilhW533yXVoft6fUuF8YR9Q+4xMQOAtmPQY+QIFHoJorQICV+jfRlMUyLPhsRo7XH6+jegIqnYvvtIiXLhNjyJcH5ykCeNIJP9SVRJ9Gui93Ame4UETi+dVPIjHjaHrHYUSp8BeFylhocF50Y2FG/gQnwLTKPHyvOk19/XYA4mce5dMN6HuSi4jVTijFaKj+s0P9KY13cCHsERQmK3glxX53fqcmAYpDgy2S67W4HfWTt2dAKlyokjdXI1rZq/wy/2SZkAMq5Utc6kx5t3EKom0ErcUlLr/ih7pdgkzP+26ItPNWnD2Df+IWNQdkOY=
  app: tasks-and-treasures-client
  on:
    repo: dermio/tasks-and-treasures-client
